// Gemini AI service - powered by Google's Generative AI
import { GoogleGenerativeAI } from '@google/generative-ai';

// Initialize Gemini AI client
let genAI: GoogleGenerativeAI | null = null;

function initializeGenAI() {
  const apiKey = process.env.NEXT_PUBLIC_GEMINI_API_KEY;
  if (apiKey && apiKey.trim().length > 0 && apiKey !== 'AIzaSyDk7ND1F0_pYw8uTh-K9G_EqZgB_3x5qPo') {
    try {
      genAI = new GoogleGenerativeAI(apiKey);
      console.log('✅ Gemini AI initialized with valid API key');
      return true;
    } catch (error) {
      console.log('⚠️  Failed to initialize Gemini AI:', error);
      return false;
    }
  } else {
    console.log('⚠️  Gemini API key not configured or is placeholder. Using mock answers.');
    return false;
  }
}

// Initialize on module load
const isGeminiReady = initializeGenAI();

export async function generateAnswer(question: string, context?: string): Promise<string> {
  // Use mock response if Gemini is not available
  if (!genAI || !isGeminiReady) {
    return generateMockAnswer(question, context);
  }

  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
    
    let prompt = '';
    
    if (context && context.length > 50) {
      // Use provided context to answer the question
      prompt = `You are an expert educational assistant. You have been provided with educational material to answer a student's question.

IMPORTANT INSTRUCTIONS:
1. Use ONLY the provided material to answer the question
2. If the material contains the answer, provide it directly with the relevant details
3. If the material doesn't contain enough information, say so clearly
4. Always cite which part of the material you're referencing
5. For exam papers: Point out relevant past exam questions and model answers
6. For textbooks: Provide clear explanations with examples from the text

EDUCATIONAL MATERIAL:
${context}

STUDENT QUESTION: "${question}"

Provide a comprehensive, well-structured answer based on the material. If the material contains definitions, formulas, or solutions, include them directly.`;
    } else {
      prompt = `You are a helpful educational assistant. Please provide a clear, concise, and accurate answer to this question.

STUDENT QUESTION: "${question}"

Provide an informative answer (2-3 paragraphs) that would be helpful for a student learning this topic.`;
    }
    
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    return text || generateMockAnswer(question, context);
  } catch (error) {
    console.error('Error with Gemini API:', error);
    return generateMockAnswer(question, context);
  }
}

export async function generateSummary(bookContent: string): Promise<string> {
  // Use mock summary if Gemini is not available
  if (!genAI || !isGeminiReady) {
    return generateMockSummary(bookContent);
  }

  try {
    const words = bookContent.split(/\s+/).length;
    
    if (words < 100) {
      return 'Content too short for summary. Please provide at least 100 words.';
    }

    const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
    const summaryPrompt = `Please create a concise summary of the following text. The summary should capture the main points and be about 30% of the original length.\n\nText to summarize:\n\n${bookContent.substring(0, 3000)}\n\nProvide only the summary without any introduction.`;

    const result = await model.generateContent(summaryPrompt);
    const response = await result.response;
    const summary = response.text();

    return summary
      ? `📖 AI-Generated Summary:\n\n${summary}\n\n[This summary was generated by Google Gemini AI]`
      : generateMockSummary(bookContent);
  } catch (error) {
    console.error('Error with Gemini API:', error);
    return generateMockSummary(bookContent);
  }
}

// Mock implementations (fallback when API is not available)
function generateMockAnswer(question: string, context?: string): string {
  // If we have context, extract relevant information from it
  if (context && context.length > 50) {
    // Extract the book title and author from context
    const bookMatch = context.match(/\[📖 From: "(.+?)" by (.+?)\]/);
    const bookTitle = bookMatch ? bookMatch[1] : 'the provided material';
    const authorName = bookMatch ? bookMatch[2] : '';
    
    // Extract key information from context
    const sentences = context
      .split(/[.!?]+/)
      .map(s => s.trim())
      .filter(s => s.length > 20 && s.length < 200)
      .slice(0, 4);
    
    let answer = `Based on the provided material from ${bookTitle}${authorName ? ` by ${authorName}` : ''}:\n\n`;
    
    // Try to match keywords from the question with context
    const questionWords = question.toLowerCase().split(/\s+/).filter(w => w.length > 3);
    
    // Find relevant sentences that contain question keywords
    const relevantSentences = sentences.filter(sentence => 
      questionWords.some(word => sentence.toLowerCase().includes(word))
    );
    
    if (relevantSentences.length > 0) {
      answer += relevantSentences.join('\n\n');
    } else {
      // If no exact match, provide the first few sentences from context
      answer += sentences.slice(0, 2).join('\n\n');
    }
    
    answer += `\n\n📌 For more detailed information, please refer to the full material or consult with your instructor.`;
    return answer;
  }
  
  // Enhanced mock answers for common questions
  const mockAnswers: Record<string, string> = {
    'newton\'s law': 
      `Newton's Laws of Motion explain how objects move and interact:\n\n1. First Law (Inertia): Objects at rest stay at rest, and objects in motion stay in motion unless acted upon by an external force.\n\n2. Second Law (F=ma): The force on an object is equal to its mass times its acceleration. Stronger forces produce greater acceleration.\n\n3. Third Law (Action-Reaction): For every action, there is an equal and opposite reaction.\n\nEveryday examples: Wearing seatbelts (First Law), accelerating a car (Second Law), and the recoil from throwing a ball (Third Law).`,
    
    'jsx':
      `JSX stands for JavaScript XML. It's a syntax extension for React that allows you to write HTML-like code in JavaScript.\n\nKey points:\n- JSX gets compiled to JavaScript function calls\n- You can embed JavaScript expressions using curly braces {}\n- JSX elements are just syntactic sugar for React.createElement()\n- Example: <div>Hello {name}</div> compiles to React.createElement('div', null, 'Hello ', name)\n\nJSX makes React code more readable and maintainable.`,
    
    'react hook':
      `React Hooks are functions that let you use state and other React features in functional components.\n\nCommon hooks:\n- useState: Manages component state\n- useEffect: Performs side effects\n- useContext: Accesses context values\n- useReducer: Manages complex state logic\n- useCallback: Memoizes callbacks\n- useMemo: Memoizes computed values\n\nHooks follow two important rules:\n1. Only call hooks at the top level\n2. Only call hooks from React function components or custom hooks`,
    
    'machine learning':
      `Machine Learning is a subset of AI where systems learn from data without being explicitly programmed.\n\nTypes of Machine Learning:\n1. Supervised Learning: Uses labeled data (e.g., classification, regression)\n2. Unsupervised Learning: Finds patterns in unlabeled data (e.g., clustering)\n3. Reinforcement Learning: Learns through rewards and penalties\n\nCommon algorithms include decision trees, neural networks, and support vector machines. ML is used in recommendation systems, image recognition, and natural language processing.`,
    
    'python data science':
      `Python is excellent for data science due to powerful libraries:\n\n- NumPy: Numerical computing and array operations\n- Pandas: Data manipulation and analysis\n- Matplotlib: Data visualization\n- Scikit-learn: Machine learning algorithms\n- Jupyter: Interactive notebooks for data exploration\n\nWorkflow: Load data with Pandas → Analyze with NumPy → Visualize with Matplotlib → Build models with Scikit-learn`,
  };

  // Search for matching key from question
  const questionLower = question.toLowerCase();
  for (const [key, answer] of Object.entries(mockAnswers)) {
    if (questionLower.includes(key)) {
      return answer;
    }
  }

  // If no exact match, provide a generic but educational response
  return `**Understanding "${question}"**\n\nThis is an important topic in learning and development. Here are key points to consider:\n\n1. **Fundamentals First**: Build a strong foundation in the basic concepts\n2. **Practice**: Apply your knowledge through practical exercises and projects\n3. **Resources**: Utilize books, online courses, and community forums\n4. **Collaboration**: Discuss and learn from peers and mentors\n5. **Consistency**: Regular study and practice lead to mastery\n\nConsider breaking down complex topics into smaller, manageable parts and gradually increase the difficulty level.\n\n💡 **Tip**: Try asking follow-up questions about specific aspects you don't understand, or request examples and use cases.`;
}


function generateMockSummary(bookContent: string): string {
  const lines = bookContent.split('\n').filter((line) => line.trim());
  const words = bookContent.split(/\s+/).length;

  if (words < 100) {
    return 'Content too short for summary. Please provide more text.';
  }

  const paragraphs = bookContent.split('\n\n');
  const summaryPoints = paragraphs.slice(0, 3).map((p) => {
    const firstSentence = p.split('.')[0];
    return firstSentence.length > 0 ? firstSentence + '.' : null;
  });

  const summary = summaryPoints
    .filter((p) => p !== null)
    .join('\n\n');

  return summary.length > 0
    ? `Summary (approx ${Math.ceil(words / 10)}% of original):\n\n${summary}\n\n[This is a generated summary. For complete understanding, please read the full text.]`
    : 'Unable to generate summary. Please try with different content.';
}
