// Gemini AI service - powered by Google's Generative AI
import { GoogleGenerativeAI } from '@google/generative-ai';

// Initialize Gemini AI client
const genAI = new GoogleGenerativeAI(process.env.NEXT_PUBLIC_GEMINI_API_KEY || '');

export async function generateAnswer(question: string, context?: string): Promise<string> {
  // Check if API key is available
  if (!process.env.NEXT_PUBLIC_GEMINI_API_KEY) {
    console.log('Gemini API key not available, using mock response');
    return generateMockAnswer(question, context);
  }

  try {
    const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
    
    let prompt = '';
    
    if (context && context.length > 50) {
      // Use provided context to answer the question
      prompt = `You are an expert educational assistant. You have been provided with educational material to answer a student's question.

IMPORTANT INSTRUCTIONS:
1. Use ONLY the provided material to answer the question
2. If the material contains the answer, provide it directly with the relevant details
3. If the material doesn't contain enough information, say so clearly
4. Always cite which part of the material you're referencing
5. For exam papers: Point out relevant past exam questions and model answers
6. For textbooks: Provide clear explanations with examples from the text

EDUCATIONAL MATERIAL:
${context}

STUDENT QUESTION: "${question}"

Provide a comprehensive, well-structured answer based on the material. If the material contains definitions, formulas, or solutions, include them directly.`;
    } else {
      prompt = `You are a helpful educational assistant. Please provide a clear, concise, and accurate answer to this question.

STUDENT QUESTION: "${question}"

Provide an informative answer (2-3 paragraphs) that would be helpful for a student learning this topic.`;
    }
    
    const result = await model.generateContent(prompt);
    const response = await result.response;
    const text = response.text();
    return text || generateMockAnswer(question, context);
  } catch (error) {
    console.error('Error with Gemini API:', error);
    return generateMockAnswer(question, context);
  }
}

export async function generateSummary(bookContent: string): Promise<string> {
  // Check if API key is available
  if (!process.env.NEXT_PUBLIC_GEMINI_API_KEY) {
    console.log('Gemini API key not available, using mock summary');
    return generateMockSummary(bookContent);
  }

  try {
    const words = bookContent.split(/\s+/).length;
    
    if (words < 100) {
      return 'Content too short for summary. Please provide at least 100 words.';
    }

    const model = genAI.getGenerativeModel({ model: 'gemini-pro' });
    const summaryPrompt = `Please create a concise summary of the following text. The summary should capture the main points and be about 30% of the original length.\n\nText to summarize:\n\n${bookContent.substring(0, 3000)}\n\nProvide only the summary without any introduction.`;

    const result = await model.generateContent(summaryPrompt);
    const response = await result.response;
    const summary = response.text();

    return summary
      ? `📖 AI-Generated Summary:\n\n${summary}\n\n[This summary was generated by Google Gemini AI]`
      : generateMockSummary(bookContent);
  } catch (error) {
    console.error('Error with Gemini API:', error);
    return generateMockSummary(bookContent);
  }
}

// Mock implementations (fallback when API is not available)
function generateMockAnswer(question: string, context?: string): string {
  // If we have context, use it to provide a better answer
  if (context && context.length > 50) {
    const contextLines = context.split('\n').filter(l => l.trim());
    const relevantLines = contextLines.slice(0, 3).join(' ');
    return `Based on the provided material:\n\n${relevantLines}\n\nRegarding your question "${question}": ${generateMockAnswer(question)}`;
  }
  
  const mockAnswers: Record<string, string> = {
    'what is nodejs':
      'Node.js is a JavaScript runtime built on Chrome\'s V8 JavaScript engine. It allows you to run JavaScript outside the browser, making it perfect for server-side development. Key features include non-blocking I/O, event-driven architecture, and npm package ecosystem.',
    'how to learn javascript':
      'To learn JavaScript effectively: 1) Master basics (variables, functions, objects) 2) Understand DOM manipulation 3) Learn async/await and Promises 4) Practice with projects 5) Study design patterns. Start with fundamentals before moving to frameworks like React or Vue.',
    'what is machine learning':
      'Machine Learning is a subset of AI where systems learn from data without being explicitly programmed. It involves training algorithms on large datasets to recognize patterns. Types include supervised learning (labeled data), unsupervised learning (unlabeled data), and reinforcement learning (learning through rewards).',
  };

  const key = question.toLowerCase().trim();
  for (const [mockKey, answer] of Object.entries(mockAnswers)) {
    if (key.includes(mockKey) || mockKey.includes(key.split(' ')[0])) {
      return answer;
    }
  }

  return `Based on the question "${question}", here's a comprehensive answer:\n\nThis is an important topic in modern education and learning. The answer depends on several factors including context, level of detail required, and specific use case.\n\nKey points to consider:\n1. Understanding fundamentals is crucial\n2. Practice and experimentation build expertise\n3. Resources and community support accelerate learning\n4. Consistency and dedication lead to mastery\n\nFor more detailed information, please consult specialized resources or ask a domain expert.`;
}

function generateMockSummary(bookContent: string): string {
  const lines = bookContent.split('\n').filter((line) => line.trim());
  const words = bookContent.split(/\s+/).length;

  if (words < 100) {
    return 'Content too short for summary. Please provide more text.';
  }

  const paragraphs = bookContent.split('\n\n');
  const summaryPoints = paragraphs.slice(0, 3).map((p) => {
    const firstSentence = p.split('.')[0];
    return firstSentence.length > 0 ? firstSentence + '.' : null;
  });

  const summary = summaryPoints
    .filter((p) => p !== null)
    .join('\n\n');

  return summary.length > 0
    ? `Summary (approx ${Math.ceil(words / 10)}% of original):\n\n${summary}\n\n[This is a generated summary. For complete understanding, please read the full text.]`
    : 'Unable to generate summary. Please try with different content.';
}
